### ISSUE TITLE
Correct command line parser

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/antler-proj#13]
UPD: Actually the first part is implemented. antler-proj work as it described here.

1. Arguments and commands should be unified similar to the description in the usecases.md. I.e. need to correct the command line parser to follow a simple syntax: 

`antler-proj <command> <path> [<args>]` 

for all commands. 

Where a `<command>` is the first word after the program name, it has no dashes, path is a path to the project and args are arguments of the command, each argument name has leading dashes.
It makes the interface logical, predictable and unified. Details see in the usecases.md and users_guide.md

UPD: I have described this problem more detailed and my view how to solve it here: https://github.com/AntelopeIO/antler-proj/pull/50#pullrequestreview-1403301593

2. Duplicates of arguments which do the same thing should be removed because for example every command has two ways to receive path to the project: 

Positionals:
  path TEXT                   This is the root path to create the project in.

Options:
  -p TEXT                     This is the root path to create the project in.

command init had 3 duplicated parameters:

Positionals:
  path TEXT REQUIRED          This is the root path to create the project in.
  project_name TEXT REQUIRED  The name of the project.
  version TEXT                The version to store in the project file.

Options:
  -p TEXT REQUIRED            This is the root path to create the project in.
  -n TEXT REQUIRED            The name of the project.
  -v TEXT                     The version to store in the project file.

**Comment by ScottBailey** [comment]
1. Required arguments should be positional. Having a flag is superfluous; however, when scripting I find it useful to have the long flag because it conveys more information to a future maintainer so there IS value to allowing these options have flags.
2. I think we can remove positional information from the optional CLI inputs.

**Comment by ScottBailey** [comment]
Additional comments based on current state of main:
- We should have `--help-all`.
- We should be consistent with help: either terminate with a period everywhere or nowhere.

See #54 for this.

**Comment by ScottBailey** [comment]
See also #51

**Comment by ScottBailey** [comment]
Consensus: all parameters become flag only. We are no longer using positional parameters.
