### ISSUE TITLE
Add --clean parameter to "build" command

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/antler-proj#18]
Issue #124 requires to add a key: 
"--clean-build-project this should remove the build directory and rebuild the project"
but the antler-proj has no such functionality.

Thus --clean parameter should be added to "build" command like: `antler-proj build <project_path> --clean`

**Comment by jolly-fellow** [comment]
I found that the option was already added in the code. I have tested its work with DUNE in the Docker container. The clean building works well.

**Comment by ScottBailey** [comment]
Confirmed. This is no longer a problem.
