### ISSUE TITLE
Incorrect processing of an empty parameter.

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/antler-proj#19]
root@c1742fb0fdb3:/app# antler-proj build /host/home/alex/dev/projects/AntelopeIO/Clion_DUNE/test ""
The following argument was not expected: 
Run with --help for more information.

This error message makes problem in cases when you don't see the command line arguments. For example when it calls from a script or another program.

**Comment by jolly-fellow** [comment]
It seems fixing of this issue will need to change CLI11.hpp around 902-915 lines, IMHO it is the problem itself because we will need to back port this change if we decide to update version of CLI11.hpp. I'd prefer don't change CLI11.hpp. How to do it? Intercept and edit an ExtrasError exception? Would it be correctly to do it in main.cpp around 77 line?

Then we need to decide which behavior with the empty arguments we want to have.
IMHO it is enough to write something like "argument [number] is empty" it allows the user to understand where is the problem when the antler-proj is starting from another program or a script, if it starts manually the problem with the command line arguments is obvious.

**Comment by larryk85** [comment]
I think doing the second proposal is fine. I.e. in main around line 77.

If we find that people are running into this an excessive amount then we can modify cli11 or other approaches.

**Comment by ScottBailey** [comment]
I think this can (and should) be achieved with a [validator](https://cliutils.github.io/CLI11/book/chapters/validators.html).

Something like this:
```cpp

add_option(whatever)->check( 
              [](const std::string& val) -> std::string { 
                        return (val.empty() ? "whatever should not be empty" :  ""); 
               } 
        );
```
