### ISSUE TITLE
Questions to the project management system design.

### ISSUE THREAD

**Issue by jolly-fellow** [AntelopeIO/antler-proj#3]
- ​May dependencies have their own dependencies and their own project.yaml?  If not, where to take their version numbers which are described in the main project.yaml and which must be checked?

- ​​​​Should dependencies be already built and ready for linking with the main project or they may be built by the build system? I.e. does the project management system build only the contract or its dependencies too?

- Why are multiple entities described in the tests section? We agreed with Scott that the project build system for doing tests of the project should calls the test system which manages all the testing processes, files and logs. In other words the project.yaml should have the only entry which describes how to call the test system. Pytest was chosen as a test system. 

- Why are multiple entities described in the app section? Does it mean that one project may manage many contracts? If yes, why not one project for one contract? It makes the design of the system much more simple. And in case of multiple contracts in one project the test entities should have some description which allows them to recognize which contract they test.

-  Should dependencies have some required features like the existence of some files, directory structure or something like this which allows to unify work with them? In other words should a dependency project have a formalized structure? After downloading remote dependencies and checking that paths to files of the local dependencies exist, should some stage of formal validation of these dependencies be done? What is a valid project? Which things should be checked to recognize the project as valid? How to recognize if the dependency is ready for use?

- Should the build system check all dependencies for updates and update them each time when it does building or by command of the user?

- Why do we have commands for removing and updating of dependencies but don't have the same for apps, libs and tests? I propose to have the only command "update" for all of them. It may do all three actions: If this command gets new info it adds it, if it already has such info it updates it, if it gets the name of the entity with empty info it removes the record with this entity. 
Format: `update <name> [info]` 
The idea is to have unified set of commands to manipulate all kinds of entities the same way. How exactly implement it may be discussed.

- Why is dependency exactly a GitHub repository? Why do we need this limitation? What should people do who want to use libraries from other services and VCS or just who have a local directory with a library or data which should be linked to the project? By the way it seems dependence on the GitHub hg tool locks Antler on GitHub service only.

- Actually app in the design description means a compiled contract ready for deploy. So why do we call it an app instead of a contract? IMHO it will confuses a user.

**Comment by stephenpdeos** [comment]
Closing this out as per @jolly-fellow in refinement
