### ISSUE TITLE
Investigate and adopt clang-format style.

### ISSUE THREAD

**Issue by ScottBailey** [AntelopeIO/antler-proj#56]
Our team Mikeł, Dima, Alex, and Scott have agreed on the value of adopting clang-format.

For this issue we want to do the following:
1. Investigate styles for adoption.
2. Apply it to all files in this repo.
3. Add clang-format to CI.

It's better that we do this sooner rather than later since this affects history and diffs.

**Comment by ScottBailey** [comment]
Related to #44

**Comment by ScottBailey** [comment]
Notes:

As I understand it, ENF wants to do this across all projects. We will be doing this sooner or later and sooner will retain the most history.

There is significant discussion about this in the Leap repos, but it stalled out due to lack of consensus. The biggest issue was the inability to arrive at line length. This should be, in my opinion, `0`. No required line length. This allows us to use whatever line length is the clearest/most intuitive. Otherwise clang-format will generate line breaks on it's own.

Before final commit, we may want to get feedback from leadership and principals (i.e. Bucky, Areg, Matt, and maybe Kevin).

**Comment by mikelik** [comment]
Note:
Before this is merged we should add pre-commit hook which automatically formats files, i.e. https://stackoverflow.com/a/57791854
