### ISSUE TITLE
antler-proj should return code between 0-255

### ISSUE THREAD

**Issue by mikelik** [AntelopeIO/antler-proj#57]
Currently if there is an error we return negative value, in below case `-1`, which gets casted to `255`
```
$ ./antler-proj add 
[error_log] :: common.hpp:load_project:27 :: path either did not exist or neither `project.yaml` nor `project.yml` file cound be found.
[error_log] :: main.cpp:main:81 :: path either did not exist or neither `project.yaml` nor `project.yml` file cound be found.
mikel@msi:~/repo/antler-proj/build/tools$ echo $?
255
```
We should return values between 0-255.

List of reserved exit codes: https://tldp.org/LDP/abs/html/exitcodes.html

**Comment by ScottBailey** [comment]
Suggestion: on error, return `EXIT_FAILURE`. It's defined as 1 for me and, probably, everyone.
