### ISSUE TITLE
antler-proj automated test fails for Ubuntu 18

### ISSUE THREAD

**Issue by ScottBailey** [AntelopeIO/antler-proj#61]
`tools/tests/populate_and_build.py` fails in Ubuntu 18 for commit e47030c9d49ba5386547fe143c8af44f958a9647.

First issue, Ubuntu 18 uses Python 3.6 and we've written our tests for 3.7. A fix for this can be seen in [this branch](https://github.com/AntelopeIO/antler-proj/blob/ubuntu_18-issue_61-python_3.6/tools/tests/populate_and_build.py).

Second issue: cmake files aren't being written. This needs investigation and a prompt correction for the 4.0 release.

**Comment by jolly-fellow** [comment]
@ScottBailey  Could you provide detailed log of the failed tests?

**Comment by jolly-fellow** [comment]
I have checked work of C++ code in debugger. It is correct. The problem is in CMake code. 
Default version of CMake in Ubuntu 18 is 3.10.2 and it work incorrect. I have installed cmake version 3.25.2 and it works correct.

**Comment by jolly-fellow** [comment]
When aproj execute
 [info_log] :: utils.hpp:execute:66 :: Command to execute = cmake -S ./proj/pandb_contract/build -B ./proj/pandb_contract/build/antler-bin
cmake doesn't generate files into antler-bin directory.

**Comment by jolly-fellow** [comment]
Oh I see cmake_minimum_required(VERSION 3.11)
in pandb_contract/build/CMakeLists.txt
but cmake doesn't report that it is older.
I just changed cmake_minimum_required(VERSION 3.11) to 3.10 and downgraded cmake to 3.10.2 and it works now.
Try on your Ubuntu 18 please.

**Comment by ScottBailey** [comment]
We also need to add `stdc++fs` back into the link libraries for Ubuntu 18 due to gcc-8 and clang-10 missing the fs library.

Here is some code to fix that for [src/CMakeLists.txt](https://github.com/AntelopeIO/antler-proj/blob/main/src/CMakeLists.txt):
```cpp
if( ((CMAKE_CXX_COMPILER_ID STREQUAL "Clang") AND (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 11))
      OR ((CMAKE_CXX_COMPILER_ID STREQUAL "GNU") AND (CMAKE_CXX_COMPILER_VERSION VERSION_LESS 9)))
   set(FSLIB stdc++fs)
endif()
```
Additionally, update `target_link_libraries` (in the same file) to add `${FSLIB}`.

**Comment by ScottBailey** [comment]
Additional analysis indicates we are using flags present only in later versions CMake. Ubuntu 18 ships with and supports CMake 3.10.2. 

`-j` requires v3.12+. Found here: [L21](https://github.com/AntelopeIO/antler-proj/blob/159b72f3b786e3d7475edce998a43448bb1ac792/tools/build.hpp#L21) and [L42-L44](https://github.com/AntelopeIO/antler-proj/blob/159b72f3b786e3d7475edce998a43448bb1ac792/tools/build.hpp#L42-L44).

`-S` and `-B` require v3.13+. Found here: [L32](https://github.com/AntelopeIO/antler-proj/blob/159b72f3b786e3d7475edce998a43448bb1ac792/tools/build.hpp#L32).

**Comment by ScottBailey** [comment]
I propose conditional compilation to work around this issue, leaving as is for Ubuntu 20+ while working around the issue in Ubuntu 18 with the expectation of removing the conditional in an upcoming release.

**Comment by ScottBailey** [comment]
See this [branch](https://github.com/AntelopeIO/antler-proj/tree/ubuntu_18-issue_61-python_3.6-2) for proposal.
